### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by albertov** [dylex/postgresql-typed#17]
We're trying to connect to a Google cloud managed Postgresql instance which only supports TLS connections but, unfortunately, postgresql-typed doesn't support it

I'm currently looking into integrating `hs-tls` to add support for it in `pgConnect` and would like to know if you're open to accepting a PR for this functionality

**Comment by dylex** [comment]
I'm definitely open to this and would be happy to help.  I made some basic changes earlier this year to the standard Network socket layer for the connection itself, which should make this easier.  (I'd still like to eliminate all the Handle use at some point but the extra layer will probably simplify tls in this case.)
