### ISSUE TITLE
Nix utils

### ISSUE THREAD

**Issue by kanishka-azimi** [dylex/postgresql-typed#8]
If you take interest in creating integration tests that compile with a test schema inside nix, you can use some of Ishaq's work using gargoyle to create a postgres instance without installing a daemon, hooking into nix build phases for the integration test exe - https://github.com/databrary/databrary/blob/obsidian-devdep/databrary.nix

Closing issue, just noted here.

**Comment by dylex** [comment]
Hi @kanishka-azimi, I just saw this, and that link seems to be dead now, but I guess maybe it's been merged in? Good to see someone building tests.  Anyway, hope you're enjoying yourself there, and feel free to email.

**Comment by kanishka-azimi** [comment]
Thanks.

You can see the key changes in databrary.nix, in the prebuild and postInstall steps, where a postgres daemon is started.
